@startuml

skinparam shadowing false
skinparam rectangleRoundCorner 5
skinparam rectangleBorderThickness 0.5

rectangle "Customer"

rectangle "Market" {
	rectangle "Item 1" <<Seller **SA**>>
	rectangle "Item 2" <<Seller **SB**>>
}

rectangle "Seller" <<**SA**>> as SA
rectangle "Seller" <<**SB**>> as SB
rectangle "Payment Gateway" <<**PGA**>> as PGA
rectangle "Payment Gateway" <<**PGB**>> as PGB
rectangle "**Nodal Account**" as Nodal

Customer -- Market
Market -- PGA
Market -- PGB
PGA -- Nodal
PGB -- Nodal
Nodal -- SA
Nodal -- SB
@enduml
