@startuml

title <b>Model v1 (states)</b>
left to right direction
skinparam shadowing false

[*] --> payment
payment --> gateway
gateway -> refund
gateway -> nodal
nodal -> seller
nodal -> marker
refund --> [*]

@enduml
