@startuml

title <b>Model v2</b>
left to right direction
skinparam shadowing false

Customer "1" -- "0..N" Order
Order "1" -- "N..1" OrderItem
Order "1" -- "N..1" Payment
OrderItem "1..N" -- "1" SellerItem
SellerItem "1..N" -- "1" Item
SellerItem "0..N" -- "1" Seller
@enduml
